# Generated by Django 2.0.3 on 2018-04-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echouser',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EchoUserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='')),
                ('sub_time', models.DateTimeField(auto_now_add=True)),
                ('sub_text', models.CharField(max_length=100, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Echouser')),
            ],
        ),
    ]
